### ISSUE TITLE
column names error

### ISSUE THREAD

**Issue by YecanLee** [MikeySaw/ara_seminar_research#4]
There is a persisting error inside the original code, which will stop the training process.
```shell
Traceback (most recent call last):
  File "train.py", line 1007, in <module>
    TT.run_folds_train(embedding_name,emb_model, tokenizer, model, optimizer, criterion, MAX_EPOCHS, device, PATIENCE, scheduler=scheduler)
  File "train.py", line 668, in run_folds_train
    dish_dict, dish_group_alignments = fetch_dish_train(dish, folder, alignment_file, recipe_folder_name, emb_model, tokenizer, device, embedding_name)
  File "/home/mainuser/alignment-models/utils.py", line 318, in fetch_dish_train
    recipe_filename, emb_model, tokenizer, device, embedding_name,
  File "/home/mainuser/alignment-models/utils.py", line 720, in fetch_recipe_train
    action_list = fetch_action_ids(parsed_recipe)  # List of actions in recipe
  File "/home/mainuser/alignment-models/utils.py", line 1061, in fetch_action_ids
    if line["xpos"].startswith("B-A")
```
The source code needes to be checked. This should be the only persistent problem we have now and will have in the future.

**Comment by YecanLee** [comment]
pass, this has been solved by adding a print in the utils.py file at line1059.
```shell
print(line)
```
it will print out the correct column name, instead of xpos it should be xpostag.
